"""thirteenth migration

Revision ID: d5145ffc886e
Revises: 68ec4b3b646e
Create Date: 2019-04-29 11:45:46.726759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5145ffc886e'
down_revision = '68ec4b3b646e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('post', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'posts', ['post'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'post')
    # ### end Alembic commands ###
